# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /users/info/etu-as/biyamouj/S2301/ProjetC++/ProjetCFaitPeauNeuve

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /users/info/etu-as/biyamouj/S2301/ProjetC++/ProjetCFaitPeauNeuve

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /users/info/etu-as/biyamouj/S2301/ProjetC++/ProjetCFaitPeauNeuve/CMakeFiles /users/info/etu-as/biyamouj/S2301/ProjetC++/ProjetCFaitPeauNeuve//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /users/info/etu-as/biyamouj/S2301/ProjetC++/ProjetCFaitPeauNeuve/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named skeleton

# Build rule for target.
skeleton: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 skeleton
.PHONY : skeleton

# fast build rule for target.
skeleton/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/build
.PHONY : skeleton/fast

models/Cercle.o: models/Cercle.cpp.o

.PHONY : models/Cercle.o

# target to build an object file
models/Cercle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Cercle.cpp.o
.PHONY : models/Cercle.cpp.o

models/Cercle.i: models/Cercle.cpp.i

.PHONY : models/Cercle.i

# target to preprocess a source file
models/Cercle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Cercle.cpp.i
.PHONY : models/Cercle.cpp.i

models/Cercle.s: models/Cercle.cpp.s

.PHONY : models/Cercle.s

# target to generate assembly for a file
models/Cercle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Cercle.cpp.s
.PHONY : models/Cercle.cpp.s

models/Dessin.o: models/Dessin.cpp.o

.PHONY : models/Dessin.o

# target to build an object file
models/Dessin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Dessin.cpp.o
.PHONY : models/Dessin.cpp.o

models/Dessin.i: models/Dessin.cpp.i

.PHONY : models/Dessin.i

# target to preprocess a source file
models/Dessin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Dessin.cpp.i
.PHONY : models/Dessin.cpp.i

models/Dessin.s: models/Dessin.cpp.s

.PHONY : models/Dessin.s

# target to generate assembly for a file
models/Dessin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Dessin.cpp.s
.PHONY : models/Dessin.cpp.s

models/Forme.o: models/Forme.cpp.o

.PHONY : models/Forme.o

# target to build an object file
models/Forme.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Forme.cpp.o
.PHONY : models/Forme.cpp.o

models/Forme.i: models/Forme.cpp.i

.PHONY : models/Forme.i

# target to preprocess a source file
models/Forme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Forme.cpp.i
.PHONY : models/Forme.cpp.i

models/Forme.s: models/Forme.cpp.s

.PHONY : models/Forme.s

# target to generate assembly for a file
models/Forme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Forme.cpp.s
.PHONY : models/Forme.cpp.s

models/Ligne.o: models/Ligne.cpp.o

.PHONY : models/Ligne.o

# target to build an object file
models/Ligne.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Ligne.cpp.o
.PHONY : models/Ligne.cpp.o

models/Ligne.i: models/Ligne.cpp.i

.PHONY : models/Ligne.i

# target to preprocess a source file
models/Ligne.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Ligne.cpp.i
.PHONY : models/Ligne.cpp.i

models/Ligne.s: models/Ligne.cpp.s

.PHONY : models/Ligne.s

# target to generate assembly for a file
models/Ligne.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Ligne.cpp.s
.PHONY : models/Ligne.cpp.s

models/Point.o: models/Point.cpp.o

.PHONY : models/Point.o

# target to build an object file
models/Point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Point.cpp.o
.PHONY : models/Point.cpp.o

models/Point.i: models/Point.cpp.i

.PHONY : models/Point.i

# target to preprocess a source file
models/Point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Point.cpp.i
.PHONY : models/Point.cpp.i

models/Point.s: models/Point.cpp.s

.PHONY : models/Point.s

# target to generate assembly for a file
models/Point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Point.cpp.s
.PHONY : models/Point.cpp.s

models/Rectangle.o: models/Rectangle.cpp.o

.PHONY : models/Rectangle.o

# target to build an object file
models/Rectangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Rectangle.cpp.o
.PHONY : models/Rectangle.cpp.o

models/Rectangle.i: models/Rectangle.cpp.i

.PHONY : models/Rectangle.i

# target to preprocess a source file
models/Rectangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Rectangle.cpp.i
.PHONY : models/Rectangle.cpp.i

models/Rectangle.s: models/Rectangle.cpp.s

.PHONY : models/Rectangle.s

# target to generate assembly for a file
models/Rectangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Rectangle.cpp.s
.PHONY : models/Rectangle.cpp.s

models/Triangle.o: models/Triangle.cpp.o

.PHONY : models/Triangle.o

# target to build an object file
models/Triangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Triangle.cpp.o
.PHONY : models/Triangle.cpp.o

models/Triangle.i: models/Triangle.cpp.i

.PHONY : models/Triangle.i

# target to preprocess a source file
models/Triangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Triangle.cpp.i
.PHONY : models/Triangle.cpp.i

models/Triangle.s: models/Triangle.cpp.s

.PHONY : models/Triangle.s

# target to generate assembly for a file
models/Triangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/models/Triangle.cpp.s
.PHONY : models/Triangle.cpp.s

skeleton.o: skeleton.cpp.o

.PHONY : skeleton.o

# target to build an object file
skeleton.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/skeleton.cpp.o
.PHONY : skeleton.cpp.o

skeleton.i: skeleton.cpp.i

.PHONY : skeleton.i

# target to preprocess a source file
skeleton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/skeleton.cpp.i
.PHONY : skeleton.cpp.i

skeleton.s: skeleton.cpp.s

.PHONY : skeleton.s

# target to generate assembly for a file
skeleton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/skeleton.cpp.s
.PHONY : skeleton.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... skeleton"
	@echo "... models/Cercle.o"
	@echo "... models/Cercle.i"
	@echo "... models/Cercle.s"
	@echo "... models/Dessin.o"
	@echo "... models/Dessin.i"
	@echo "... models/Dessin.s"
	@echo "... models/Forme.o"
	@echo "... models/Forme.i"
	@echo "... models/Forme.s"
	@echo "... models/Ligne.o"
	@echo "... models/Ligne.i"
	@echo "... models/Ligne.s"
	@echo "... models/Point.o"
	@echo "... models/Point.i"
	@echo "... models/Point.s"
	@echo "... models/Rectangle.o"
	@echo "... models/Rectangle.i"
	@echo "... models/Rectangle.s"
	@echo "... models/Triangle.o"
	@echo "... models/Triangle.i"
	@echo "... models/Triangle.s"
	@echo "... skeleton.o"
	@echo "... skeleton.i"
	@echo "... skeleton.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

